/**
 * The demo's content directory, built by Eleventy with the config the docs
 * hand a site.
 *
 * `packages/cms/test/eleventy.test.ts` makes the same comparison over the
 * package's fixtures; this one makes it over the content a person would
 * actually recognise as a site, and over the demo's own `_includes` layouts.
 * If the two ever disagree with the CMS about where a document lives, a site
 * that left Geekity for a static build would find its URLs moved.
 *
 * The content is copied somewhere writable and built there, because Eleventy
 * resolves the config's relative paths and its output directory against the
 * working directory, and that must not be the repository. The config itself is
 * loaded from `apps/demo/eleventy.config.js` where it sits: it re-exports the
 * documented example, and that relative import has to keep resolving.
 */
import assert from 'node:assert/strict';
import { cp, mkdtemp, readdir, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { after, before, describe, it } from 'node:test';

import Eleventy from '@11ty/eleventy';
import { frontPageSlugs, isPublicDocument, parseDocument } from '@geekity/cms';
import type { Document, FrontPageSlugs, SiteData } from '@geekity/cms';

/** The demo site's root: what a site runs `npx @11ty/eleventy` from. */
const PROJECT_DIR = fileURLToPath(new URL('../', import.meta.url));
const CONTENT_DIR = path.join(PROJECT_DIR, 'content');
const CONFIG_PATH = path.join(PROJECT_DIR, 'eleventy.config.js');

/** Feeds are generated by the CMS in code, not by a template, so neither side builds them. */
const FEED_PATTERN = /^feed\.[^/]+$/;

/** Directories under `content/` that hold no documents. */
const NOT_DOCUMENTS = new Set(['_data', '_includes', 'uploads']);

/** Every Markdown document in the demo content, parsed the way the CMS reads it. */
async function demoDocuments(): Promise<Document[]> {
  const documents: Document[] = [];

  for (const relativePath of await markdownPaths(CONTENT_DIR, '')) {
    const source = await readFile(path.join(CONTENT_DIR, relativePath), 'utf8');
    documents.push(parseDocument(source, { path: relativePath }));
  }

  return documents;
}

/** Content-relative paths of every Markdown file that is a document. */
async function markdownPaths(directory: string, prefix: string): Promise<string[]> {
  const found: string[] = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relativePath = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      if (NOT_DOCUMENTS.has(entry.name)) continue;
      found.push(...(await markdownPaths(path.join(directory, entry.name), relativePath)));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.md')) found.push(relativePath);
  }

  return found.sort();
}

/** Output-relative paths of every file Eleventy wrote, with `/` separators. */
async function outputPaths(directory: string, prefix = ''): Promise<string[]> {
  const found: string[] = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const relativePath = prefix === '' ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      found.push(...(await outputPaths(path.join(directory, entry.name), relativePath)));
      continue;
    }
    if (entry.isFile()) found.push(relativePath);
  }

  return found.sort();
}

/** The file Eleventy should write for a permalink: `/a/b/` becomes `a/b/index.html`. */
function outputPathFor(permalink: string): string {
  return `${permalink.replace(/^\//, '')}index.html`;
}

/**
 * The Reading choice the demo makes: which page the site serves at `/`, and
 * which one carries the listing. Read out of the same `site.json` the build
 * reads, through the CMS's own reader, so the two cannot disagree.
 */
async function reading(): Promise<FrontPageSlugs> {
  const file = await readFile(path.join(CONTENT_DIR, '_data', 'site.json'), 'utf8');
  return frontPageSlugs(JSON.parse(file) as SiteData);
}

describe('the demo content directory under Eleventy', () => {
  let buildDir: string;
  let written: string[];
  let documents: Document[];
  let picks: FrontPageSlugs;
  const originalCwd = process.cwd();

  before(async () => {
    documents = await demoDocuments();
    picks = await reading();

    buildDir = await mkdtemp(path.join(tmpdir(), 'geekity-demo-11ty-'));
    await cp(CONTENT_DIR, path.join(buildDir, 'content'), { recursive: true });

    // The example config honours BUILD_DRAFTS as a local preview escape hatch.
    // The comparison is about the published site, so it never applies.
    delete process.env['BUILD_DRAFTS'];

    process.chdir(buildDir);
    try {
      const eleventy = new Eleventy('content', '_site', {
        configPath: CONFIG_PATH,
        quietMode: true,
      });
      await eleventy.write();
    } finally {
      process.chdir(originalCwd);
    }

    written = await outputPaths(path.join(buildDir, '_site'));
  });

  after(async () => {
    process.chdir(originalCwd);
    if (buildDir !== undefined) await rm(buildDir, { recursive: true, force: true });
  });

  it('builds the demo site without errors', () => {
    assert.ok(written.length > 0, 'Eleventy wrote nothing');
    assert.ok(
      written.some((file) => file.endsWith('index.html')),
      `no page was written: ${written.join(', ')}`,
    );
  });

  it('writes every published document where the CMS serves it', () => {
    // The CMS's own public predicate, so this comparison keeps meaning "what
    // the site serves" as that grows: drafts, the trash, and a post whose date
    // has not arrived (which the example config's preprocessor leaves out too).
    const published = documents.filter((document) => isPublicDocument(document));
    assert.ok(published.length >= 8, 'the demo does not exercise enough documents');

    for (const document of published) {
      assert.ok(
        written.includes(outputFor(document)),
        `${document.path} is served at ${servedAt(document)}, so Eleventy should have written ` +
          `${outputFor(document)}; it wrote ${written.join(', ')}`,
      );
    }
  });

  it('writes nothing the CMS would not serve at that URL', () => {
    const expected = new Set(
      documents
        .filter((document) => isPublicDocument(document))
        .map((document) => outputFor(document)),
    );

    const unexplained = written.filter(
      (file) => !expected.has(file) && !FEED_PATTERN.test(file) && !file.startsWith('uploads/'),
    );

    assert.deepEqual(unexplained, []);
  });

  it('leaves the demo draft out of the build', () => {
    const drafts = documents.filter((document) => document.draft);
    assert.ok(drafts.length > 0, 'the demo has no draft to exclude');

    for (const draft of drafts) {
      assert.ok(
        !written.includes(outputPathFor(draft.permalink)),
        `${draft.path} is a draft but Eleventy wrote ${outputPathFor(draft.permalink)}`,
      );
    }
  });

  /**
   * The URL the CMS serves one document at: `/` for the page the Reading
   * setting makes the homepage (TASK-74), and its own permalink for every
   * other one. The example config builds the same way, which is the whole
   * point of the comparison.
   */
  function servedAt(document: Document): string {
    return document.slug === picks.homepage ? '/' : document.permalink;
  }

  /** The file Eleventy should write for it. */
  function outputFor(document: Document): string {
    return outputPathFor(servedAt(document));
  }

  it('renders a post through the demo layout in content/_includes', async () => {
    const html = await readFile(
      path.join(buildDir, '_site', outputPathFor('/2026/08/markdown-on-disk/')),
      'utf8',
    );

    assert.match(html, /<h1>Markdown on disk<\/h1>/);
    // The body is Markdown rendered as Markdown, not as a template: a `{{ … }}`
    // in a post means one thing in the CMS and the same thing here.
    assert.match(html, /<code class="language-js">/);
  });
});
