/**
 * Writes `src/seed.ts` from a `tag,followers` export of tags.pub accounts
 * followed on a Mastodon server:
 *
 *   pnpm --filter @geekity/plugin-tag-suggest seed <export.csv> --source "<where it came from>" --date <YYYY-MM-DD>
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

import { seedTags } from './seed.ts';

const MINIMUM_FOLLOWERS = 2;

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: { source: { type: 'string' }, date: { type: 'string' } },
});
const [csvPath] = positionals;
const { source, date } = values;
if (csvPath === undefined || source === undefined || date === undefined) {
  throw new Error('Usage: build-seed.ts <export.csv> --source "<where>" --date <YYYY-MM-DD>');
}
if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) throw new Error(`--date ${date} is not YYYY-MM-DD`);

const denylist = readFileSync(new URL('denylist.txt', import.meta.url), 'utf8');
const tags = seedTags(readFileSync(csvPath, 'utf8'), denylist, MINIMUM_FOLLOWERS);

const out = fileURLToPath(new URL('../src/seed.ts', import.meta.url));
writeFileSync(
  out,
  `/**
 * Hashtags people follow, for suggestions that reach readers: generated by
 * \`scripts/build-seed.ts\` from the export named in \`source\`. Each count is
 * the followers the tag's tags.pub account had from that one server, so it
 * ranks the tags against each other rather than counting everyone. Tags with
 * fewer than ${String(MINIMUM_FOLLOWERS)} followers, tags.pub's service accounts and the tags in
 * \`scripts/denylist.txt\` are left out. Rebuild it rather than edit it.
 */
export const SEED: {
  readonly source: string;
  readonly date: string;
  readonly tags: readonly (readonly [name: string, followers: number])[];
} = ${JSON.stringify({ source, date, tags })};
`,
);
execFileSync('pnpm', ['exec', 'prettier', '--write', out], { stdio: 'inherit' });
console.log(`Wrote ${String(tags.length)} tags to ${out}.`);
